import { Roboto } from 'next/font/google'
import './globals.css'
import Layout from '@/layout/layout'

const roboto = Roboto({ subsets: ['latin'], weight: "100" })

export const metadata = {
  title: 'CaFee',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="fa" dir='rtl'>
     <body className={roboto.className}>
        <Layout >
          {children}
        </Layout>
      </body>
    </html>
  )
}
